BACKUP
BACKUP
BACKUP
BACKUP
WRITE [(lekzt,l2iir76u)]
READ [euugj,vlxod,lhvlv,sxoix]
DELETE [fdhww,uegkx,cogcl,wwhwi]
DELETE [lmdwg,kkjzi,xktin,xzsyb]
READ [zhbal,ncepx,tqpqx]
READ [vdezp]
WRITE [(kyird,twz9mtde)(dumai,v843lckw)(lmxfl,sbl9vsg1)(fjggs,0l1ggfvs)(epkhk,ht4gyqcm)]
READ [lqjfn,demlv]
READ [aixva,nesmi,ytimz,bhooh]
DELETE [dpcgn,lwyyg,iqygp]
BACKUP
READ [mpaue,fscpg,yricq,cmysa]
WRITE [(giewb,rowpvuvw)(nreus,fj896pjv)]
SHOW
SHOW
BACKUP