WRITE [(ndxmr,008c5aos)(osqqv,7xr1bgcy)(qyunh,s3ym6aid)]
WRITE [(qrvux,ekeoxfos)(bcepu,5we8bztk)(pahwx,vf3i7671)]
BACKUP
WRITE [(txccr,v8hn6qez)(updyq,0ems37z6)]
WRITE [(nuzhq,r5oteaia)(degby,bhh9hm35)(vdvqx,brkv125m)]
DELETE [uphyy]
DELETE [uuwwc,ymdox,guqqp]
SHOW
DELETE [xfpmq,wbvqw,lpihj]
BACKUP
SHOW
SHOW
DELETE [tfxxu,iqyin,mmjjk]
READ [fijtp,caywn,lxsdc,iwrul]
BACKUP
SHOW
SHOW
BACKUP
WRITE [(jksfx,xzvvl242)(spsav,izc94wt0)(vteee,0089q6za)(gsuyt,kktuqnwi)(rrtca,qt1ddd8z)]
BACKUP
