DELETE [alnaj,rmomv]
DELETE [ksqsu,mtrqm,etcjd]
BACKUP
BACKUP
DELETE [jtvgm,qdomc,kobnq]
READ [txcrs,bjrji,adlfl]
SHOW
DELETE [ywxkj]
SHOW
WRITE [(mbfgy,ptldcepu)(wokaj,otmqjgb5)]
WRITE [(pzdrr,vw8o7jir)]
READ [awaxd,foxjb,rnnpq,xhmvg]
READ [xjkxz,rizxg,vptzl,scbda]
WRITE [(yacyy,4q3yxps4)(npvbj,72dpiuy1)(tdyql,lurmu8en)(khecv,jxuoq7hq)(ywmim,uhs5zjug)]
READ [iupic,kodhp,xoooe,ijblc]
WRITE [(tdutp,b9woucb1)(poyfr,upmah6i2)(fdobn,mm191rd4)(tmwul,czuhnoti)]
BACKUP
BACKUP
BACKUP
BACKUP
