BACKUP
DELETE [pzxno,aqjet,utiyr,wjlvu,xatux]
DELETE [imgfb,pawjk]
SHOW
SHOW
DELETE [ncrlp,xogjx,ikgpi,nvdbe,dwkco]
READ [yqnyt,dswia,hzwbo,avuvz,npmei]
BACKUP
WRITE [(qrryn,vjbwmxu6)(wfjka,81mq4nqc)(yomwi,q9izvub9)(fvqxz,7hrrxcn6)(kczma,kti6zg23)]
DELETE [gbbml,rbmdd]
READ [camvp,okvib,ogbnn,vnouf]
DELETE [rptpb,xbjef,edurf,yjodq,geqdi]
SHOW
READ [imwkb]
BACKUP
SHOW
DELETE [ygaii,glkhl,anzcb,ngype]
WRITE [(kesje,h0ke3j9d)(acjzq,epehpefh)(bxjvv,9vui8hcr)(pnnxu,abq27rn1)]
SHOW
BACKUP
