SHOW
DELETE [fertj,bzqwn,soaki,quxaa,rivoa]
SHOW
SHOW
SHOW
WRITE [(pqekb,i06jn878)(gqsag,6bskxv4v)(lpvum,k7146zyq)(eefsg,pogcwey5)(uvjfh,lzrtztoi)]
READ [okxgd,ebeai,edezn]
SHOW
WRITE [(omgcs,fuac33il)(aqkdp,h0w2d18d)(graqr,wntkc9ep)]
READ [zjazr,wfrya,eygkv,lnsyg,edjmp]
SHOW
SHOW
READ [rvwsp]
BACKUP
DELETE [ectuz,ftvyk,qtrny]
READ [awaye,rxbdg,zfwqy,lsnwm,gatab]
READ [pidat,myhfy,ngghn,rdufx]
WRITE [(izxoi,7ww03lws)(yurpb,4wup0usu)]
READ [ktxgv,ejamz,quuuk]
BACKUP