READ [yiips,onxpd,lzsae,ruugh,zabpd]
DELETE [rxwog,fnagd,gshtv,psyja,oixbz]
READ [glyly,eayvj,pxqvt]
BACKUP
BACKUP
WRITE [(axweh,jlpu0ixe)]
BACKUP
SHOW
SHOW
DELETE [qcccg,ciapr]
SHOW
WRITE [(dopro,3icqs98t)(knswt,9x17grwn)(ybriw,4p6fhs22)(klxzl,7yikppao)]
READ [nlekz]
DELETE [xvefd,vezrn,iroth,zikkz,mxrwl]
DELETE [rfmkm]
READ [ohchv,vygcw,rubqj]
SHOW
DELETE [muyba,rhiva,npzhb]
BACKUP
DELETE [wnebu]
