DELETE [mudoa,srtgp,lbspn,nbalc,cqzmt]
SHOW
READ [xatby,schcy,pikmh,pweca]
READ [ououe,srmnx,izwkm,wberu]
BACKUP
READ [zkcgr,ubvbk,gaqgz,xdvzs,grcdl]
BACKUP
READ [qhxst,pqhqx,mdotd,reamy]
READ [dclpt,qerbu,pgwbe]
WRITE [(gdtvu,usbtnfby)]
DELETE [ygysk,ykren,dafbo,brqbw]
READ [dnfpv]
READ [oyfgb,kiery,ztmxp]
SHOW
WRITE [(mwhpx,pc2xgc8e)(tgoly,rn92nl0s)(eescj,jjp99hxk)(nwnki,bkzhg5p4)]
DELETE [jxsqm,pkrhk,wgbdy,bqogu]
DELETE [znggf,qlrry,bioqt,snhmj]
SHOW
WRITE [(gokjn,67g10as7)]
SHOW